### ISSUE TITLE
Vulnerabilidade nas Biblioteca axios@0.21.1  e follow-redirects@1.13.1

### ISSUE THREAD

**Issue by leandro-costa-oliveira** [franciscotfmc/gn-api-sdk-node#27]
A bibiloteca axios@0.21.1, utilizada pela lib, está com uma vulnerabilidade conhecida. 

Idealmente é necessário atualizá-las, 
- axios@0.21.1 para pelo menos axios@0.21.3

Fonte: 
- https://security.snyk.io/vuln/SNYK-JS-AXIOS-1579269
- https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-2332181

**Comment by jvoliveiraGN** [comment]
Obrigado pelo feedback @leandrocostaoliveira :)
Corrigido na Release 3.0.2
